export enum AzureSettingsKeys {
  ADMIN_APP_SECRET = 'ADMIN_APP_SECRET',
  ADMIN_CLIENT_ID = 'ADMIN_CLIENT_ID',
  TENANT_ID = 'TENANT_ID',
  USER_GROUP_ID = 'USER_GROUP_ID',
  AD_DOMAIN = 'AD_DOMAIN',
}
