export enum AzureSettingsKeys {
  ARM_CLIENT_SECRET = 'ARM_CLIENT_SECRET',
  ARM_CLIENT_ID = 'ARM_CLIENT_ID',
  TENANT_ID = 'TENANT_ID',
  USER_GROUP_ID = 'USER_GROUP_ID',
  AD_DOMAIN = 'AD_DOMAIN',
}
